import Link from "next/link";

const resources = [
  {
    title: "System Prompts",
    desc: "7 specialized prompts defining the classifier and six interpretive lenses. Each includes constitutional grounding, scoring rubrics, and output format specifications.",
    count: "7 files, ~2,800 lines",
    type: "Prompts",
    href: "/scholars/prompts",
  },
  {
    title: "Scoring Schema",
    desc: "JSON Schema defining the output structure for all evaluations, including score cells, confidence levels, relevance ratings, and narrative fields.",
    count: "1 file",
    type: "Schema",
    href: "/scholars/schema",
  },
  {
    title: "Integrity Tests",
    desc: "40 tests verifying scoring symmetry across partisan lines and invariance across different framings of the same action.",
    count: "25 symmetry pairs + 15 framing tests",
    type: "Testing",
    href: "/scholars/integrity",
  },
];

export default function ScholarsPage() {
  return (
    <div className="mx-auto max-w-6xl px-6 py-12">
      <div className="mb-12">
        <h1 className="font-serif text-3xl font-bold text-slate-900 tracking-tight">
          For Scholars
        </h1>
        <p className="mt-2 text-sm text-slate-500 max-w-2xl">
          Full access to the prompts, schemas, and integrity testing framework
          behind every CFI evaluation. Everything is readable, auditable, and
          forkable.
        </p>
      </div>

      {/* Resources */}
      <section className="mb-16">
        <h2 className="font-serif text-xl font-semibold text-slate-900 mb-6">
          Open Resources
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {resources.map((r) => (
            <Link
              key={r.title}
              href={r.href}
              className="group block p-5 rounded-lg border border-slate-200 bg-white hover:shadow-md transition-shadow"
            >
              <span className="text-xs font-medium text-indigo-600 uppercase tracking-wider">
                {r.type}
              </span>
              <h3 className="mt-2 text-sm font-semibold text-slate-800 group-hover:text-indigo-700 transition-colors">
                {r.title}
              </h3>
              <p className="mt-2 text-sm text-slate-500 leading-relaxed">
                {r.desc}
              </p>
              <div className="mt-3 flex items-center justify-between">
                <span className="text-xs text-slate-400">{r.count}</span>
                <span className="text-xs text-indigo-600 font-medium group-hover:text-indigo-500 transition-colors">
                  View &rarr;
                </span>
              </div>
            </Link>
          ))}
        </div>
      </section>

      {/* Governance */}
      <section className="mb-16">
        <h2 className="font-serif text-xl font-semibold text-slate-900 mb-6">
          Governance Model
        </h2>
        <div className="bg-white rounded-lg border border-slate-200 p-6">
          <div className="space-y-4 text-sm text-slate-600 leading-relaxed">
            <p>
              The CFI operates under a principle of radical transparency. All
              system prompts, scoring rubrics, aggregation algorithms, and
              integrity tests are publicly available for inspection and
              criticism.
            </p>
            <p>
              Evaluations are generated by AI using structured prompts. The
              system is designed to be auditable — any researcher can reproduce
              evaluations using the published prompts and verify scores against
              the aggregation pipeline.
            </p>
            <p>
              Integrity testing includes partisan symmetry pairs (ensuring
              similar actions by different administrations receive similar
              scores) and framing invariance tests (ensuring different
              descriptions of the same action produce consistent results).
            </p>
          </div>
        </div>
      </section>

      {/* Architecture */}
      <section>
        <h2 className="font-serif text-xl font-semibold text-slate-900 mb-6">
          Architecture Overview
        </h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { label: "Executive Orders", value: "26" },
            { label: "Interpretive Lenses", value: "6" },
            { label: "Constitutional Dimensions", value: "7" },
            { label: "Scoring Cells", value: "1,092" },
          ].map((stat) => (
            <div
              key={stat.label}
              className="p-4 rounded-lg border border-slate-200 bg-white text-center"
            >
              <p className="text-2xl font-bold font-serif text-slate-900">
                {stat.value}
              </p>
              <p className="mt-1 text-xs text-slate-500">{stat.label}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
