import Link from "next/link";

export default function AboutPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-12">
      <h1 className="font-serif text-3xl font-bold text-slate-900 tracking-tight">
        About CFI
      </h1>
      <p className="mt-4 text-sm text-slate-600 leading-relaxed">
        The Constitutional Fidelity Index is an analytical framework for
        evaluating executive actions against constitutional principles. It is
        not a legal determination, a partisan ranking tool, or a substitute
        for professional legal analysis.
      </p>

      {/* What CFI Is */}
      <section className="mt-10">
        <h2 className="font-serif text-xl font-semibold text-slate-900 mb-3">
          What CFI Is
        </h2>
        <ul className="space-y-2 text-sm text-slate-600 leading-relaxed">
          <li>
            An analytical framework that applies six constitutional interpretive
            frameworks to executive actions, producing structured evaluations
            across seven constitutional dimensions.
          </li>
          <li>
            AI-generated analysis using transparent, published prompts. Every
            evaluation includes full narratives and raw scoring data for
            independent verification.
          </li>
          <li>
            A tool for structured thinking about constitutional questions &mdash;
            surfacing where interpretive frameworks agree, where they diverge,
            and what the strongest constitutional defense looks like.
          </li>
        </ul>
      </section>

      {/* What CFI Is Not */}
      <section className="mt-10">
        <h2 className="font-serif text-xl font-semibold text-slate-900 mb-3">
          What CFI Is Not
        </h2>
        <ul className="space-y-2 text-sm text-slate-600 leading-relaxed">
          <li>
            <strong className="text-slate-800">Not a legal determination.</strong>{" "}
            No constitutional &ldquo;conflict&rdquo; or &ldquo;alignment&rdquo;
            exists until a court rules. CFI floor assessments reflect analytical
            consensus across interpretive frameworks, not judicial findings.
          </li>
          <li>
            <strong className="text-slate-800">Not a partisan ranking tool.</strong>{" "}
            Comparing average scores across administrations conflates different
            types of actions and is methodologically invalid. Each evaluation
            should be read on its own terms.
          </li>
          <li>
            <strong className="text-slate-800">Not a substitute for legal analysis.</strong>{" "}
            CFI evaluations are generated by AI models applying structured
            constitutional reasoning. They are not reviewed by constitutional
            scholars or practicing attorneys.
          </li>
        </ul>
      </section>

      {/* Known Limitations */}
      <section className="mt-10">
        <h2 className="font-serif text-xl font-semibold text-slate-900 mb-3">
          Known Limitations
        </h2>
        <div className="space-y-4 text-sm text-slate-600 leading-relaxed">
          <div>
            <p className="font-medium text-slate-800">
              Dimension selection is editorial.
            </p>
            <p className="mt-1">
              The seven constitutional dimensions (Rights, Equal Protection,
              Democratic Process, Separation of Powers, Due Process, Welfare,
              Sovereignty) are choices, not discoveries. Alternative frameworks
              would weight different aspects of constitutional analysis.
              Federalism and enumerated powers are not standalone dimensions in
              the current version.
            </p>
          </div>
          <div>
            <p className="font-medium text-slate-800">
              AI dependency and hallucination risk.
            </p>
            <p className="mt-1">
              Evaluations are generated by large language models that may
              hallucinate case citations, misstate holdings, or produce
              inconsistent results across runs. Case citations in lens narratives
              should not be treated as verified legal research.
            </p>
          </div>
          <div>
            <p className="font-medium text-slate-800">Sample bias.</p>
            <p className="mt-1">
              100 executive orders across four administrations is not
              comprehensive. The selection itself reflects editorial judgment
              about which actions are constitutionally significant. Administrations
              with more evaluated actions are not necessarily more constitutionally
              problematic &mdash; they may simply have more actions deemed worth
              evaluating.
            </p>
          </div>
          <div>
            <p className="font-medium text-slate-800">
              Calibration limits.
            </p>
            <p className="mt-1">
              CFI includes a{" "}
              <Link href="/scholars/integrity" className="text-indigo-600 hover:text-indigo-500">
                bias calibration system
              </Link>{" "}
              that detects and corrects for partisan asymmetry across
              interpretive frameworks. However, this system cannot detect bias
              shared uniformly across all frameworks &mdash; only differential
              bias between them.
            </p>
          </div>
          <div>
            <p className="font-medium text-slate-800">Reproducibility.</p>
            <p className="mt-1">
              LLM outputs are non-deterministic. Re-running evaluations with
              different model versions, temperatures, or even the same
              configuration on different days could produce materially different
              scores. Published evaluations reflect a specific generation run and
              are not re-run without versioning.
            </p>
          </div>
        </div>
      </section>

      {/* Appropriate Use */}
      <section className="mt-10">
        <h2 className="font-serif text-xl font-semibold text-slate-900 mb-3">
          Appropriate Use
        </h2>
        <ul className="space-y-2 text-sm text-slate-600 leading-relaxed">
          <li>
            Use CFI to understand how different constitutional philosophies
            evaluate an executive action. The lens narratives and disagreement
            data are more informative than the score alone.
          </li>
          <li>
            Pay attention to the consensus level. An evaluation with
            &ldquo;Significant Disagreement&rdquo; across frameworks is making a
            weaker claim than one with &ldquo;Broad Consensus.&rdquo;
          </li>
          <li>
            Do not cite CFI scores as evidence that an executive action is
            constitutional or unconstitutional. The score is an analytical
            summary, not a legal conclusion.
          </li>
        </ul>
      </section>

      <div className="mt-12 pt-8 border-t border-slate-200">
        <div className="flex gap-4 text-sm">
          <Link
            href="/methodology"
            className="text-indigo-600 hover:text-indigo-500 font-medium transition-colors"
          >
            Full methodology &rarr;
          </Link>
          <Link
            href="/scholars/integrity"
            className="text-indigo-600 hover:text-indigo-500 font-medium transition-colors"
          >
            Integrity tests &rarr;
          </Link>
        </div>
      </div>
    </div>
  );
}
